### ISSUE TITLE
WhatsApp business key

### ISSUE THREAD

**Issue by luiscadeira** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#100]
Hi, my name is Luis.

I'm from Brazil.

It would have the version for WhatsApp business.

I'm in need of a KEY, but I can't root my smartphone.

And with this APP, it's the best option I have at the moment.

thanks.

**Comment by YuvrajRaghuvanshiS** [comment]
It does not work on whatsapp business version. What you can do is log in to regular WhatsApp and use this.
