### ISSUE TITLE
I am Portuguese I have a doubt I'm using the translator so there must be Portuguese errors in the doubt of decrypt14 later versions

### ISSUE THREAD

**Issue by BrunoHenrique229** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#101]
Funcionou perfeitamente aqui para mim consegui fazer, o processo conseguiu obter a minha chave na versão antiga do whatspp instalada, através do software seu, deu tudo certo, até consegui descriptografar os arquivos msgstore.db.crypt14 e a chave pelo whatsapp visualizador até agora tudo bem, mas fato é que esse procedimento pode parar de funcionar algum dia? ah se isso acontecer você vai conseguir se alguma solução pra contornar se ouver algum problema futuramente? se no futuro, esse procedimento falhar e não puxar a chave por exemplo?

This message is from a Brazilian please translate to understand and answer me if possible

**Comment by YuvrajRaghuvanshiS** [comment]
Yes, ADB backup is deprecated and will be removed from future builds of Android. When that happens, this tool will not work on those newer version. It will continue to work on the Android version on which it is working currently (I hope). I currently have no workaround as of now when that happens.
