### ISSUE TITLE
How is the application decrypting the backups?

### ISSUE THREAD

**Issue by dmdhrumilmistry** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#102]
How is this project decrypting the crypt14 and crypt15 files?

**Comment by YuvrajRaghuvanshiS** [comment]
it does not. It instead pulls the plaintext files from the app data directory.

**Comment by dmdhrumilmistry** [comment]
So it'll copy all the files from /data/data/com.whatsapp ?

**Comment by YuvrajRaghuvanshiS** [comment]
yes, using `--tar-only` flag you'd be able to view all those.

**Comment by dmdhrumilmistry** [comment]
> yes, using `--tar-only` flag you'd be able to view all those.

thanks for the information
