### ISSUE TITLE
SDK 19 doesn't support runtime permissions

### ISSUE THREAD

**Issue by lucas75018** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#103]
Hello folks,

I am getting a

```
Performing Streamed Install
adb: failed to install tmp\LegacyWhatsApp.apk: Failure [-26: Package com.whatsapp new target SDK 19 doesn't support runtime permissions but the old target SDK 31 does.]
```

on WhatsApp-Key-DB-Extractor-master with Android 12 (Realme RMX3393).
Using the WhatsApp Messenger Version 2.11.431 APK file.

Any ideas how to cirumvent that or what else to try?

**Comment by YuvrajRaghuvanshiS** [comment]
try running with `--allow-reboot` flag.
