### ISSUE TITLE
no error msgs just "logs" in Samsung A53 and all was deleted!

### ISSUE THREAD

**Issue by Tremend0** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#104]
**Describe the bug**
I followed the instructions for a Samsung S5. Everything worked fine, and I got the db and key. No problem.
Then I did the same for a Samsung A53. I did the backup of course. And then I ran Whatsapp-Key-Database-Extractor. Everything SEEMED fine, with no error messages. However the corresponding tar file doesn't have any db folder, just logs.
Then I looked in the tar, the file /apps/com.whatsapp/f/Logs/whatsapp.log
It shows two **open failed: EACCES (Permission denied)** and one **UNCAUGHT EXCEPTION**
That did worry me a lot. So I opened my Samsung A53 Whatsapp and it said "you need to register your device, please write your phone number". I did it, Whatsapp turned on COMPLETELY EMPTY!!!
I lost all my chats!!!
Help me please!

**To Reproduce**
1. run '..'
2. Enter '..'
3. See error

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/49019911/212556975-69db0576-58a5-4499-80bb-6da029c67eb7.png)

![image](https://user-images.githubusercontent.com/49019911/212557284-ccb1b995-5013-41ca-af77-92c122ede990.png)

**Terminal output or log file**
```
Copy paste terminal output here or drag and drop "log/wa_kdbe.log"
[wa_kdbe.log](https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/files/10420815/wa_kdbe.log)

Now the file ~/WhatsApp-Key-Database-Extractor/extracted/apps/com.whatsapp/f/Logs/whatsapp.log
[whatsapp.log](https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/files/10420845/whatsapp.log)


```

**Additional context**

**Comment by YuvrajRaghuvanshiS** [comment]
That was unexpected, I have not been following this for a long time so can't say for sure exactly what happened.
As you said you have backed up the whatsapp, during registration didn't that restore?
