### ISSUE TITLE
Test on S22 shows issue with starting of legacy WA-App

### ISSUE THREAD

**Issue by hahn23** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#107]
I tried your Extractor today on my new S22 galaxy. The Script passed all the checks, but at the end I just got an 1kb .ab file.

So i tried all the steps manually and found the little detail which prevents all from working probably.

After installing the legagy whatsapp apk, your script starts it, to let it create the needed files etc.
but on the very first start, my galaxy showed an kind of Error "App was developed for an lower android version...",
which I had to skip and then starting the legacy app second time. to let it even run the process.

So after that, I could create an full size .ab file without any problem and with the key file inside etc.

I think you just would have to run the legacy app 2-3 times to be sure it was at least started once.

Thats all I discovered and I wanted to share this information with you to improove your excelent work even more.

**Comment by shiv391patel** [comment]
did all process correctly getting this error as shown in screen shot
![image](https://user-images.githubusercontent.com/93057554/219940358-90c1ca0a-0957-472b-9f75-8dd2ce1dd476.png)
