### ISSUE TITLE
"Unexpected end of data" when extracting tar

### ISSUE THREAD

**Issue by Frankprog03** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#111]
Everything works fine until it comes to the final extraction of the tar archive. It is probably corrupted and I have no idea if it is caused by abe.jar or something else. I tried backing up at least 10 times trying with and without the backup password, but I get every time the same result. Extraction of the tar with third party software such as 7zip yields the same.

This is the log of the last stage of the script:

```
[Wednesday 03/05/2023, 16:34:37] >>> I am in view_extract.extract_ab(is_java_installed=True, is_tar_only=False)
[Wednesday 03/05/2023, 16:34:37] Found "whatsapp.ab" in "tmp" folder. Continuing... Size: 594847464 bytes.
[Wednesday 03/05/2023, 16:34:37] Enter a name for this user (default "user").: 
[Wednesday 03/05/2023, 16:34:37] Enter same password which you entered on device when prompted earlier.: ********
[Wednesday 03/05/2023, 16:34:37] Successfully unpacked "tmp/whatsapp.ab" to "tmp/whatsapp.tar". Size: 1358559744 bytes.
[Wednesday 03/05/2023, 16:34:37] >>> I am in view_extract.taking_out_main_files(username=user)
[Wednesday 03/05/2023, 16:34:37] Folder "extracted/" already exists.
[Wednesday 03/05/2023, 16:34:37] Folder "extracted/user" already exists.
[Wednesday 03/05/2023, 16:34:37] Taking out main files in "tmp/" folder temporarily.
[Wednesday 03/05/2023, 16:34:37] unexpected end of data
[Wednesday 03/05/2023, 16:34:37] >>> I am in view_extract.clean_tmp()
[Wednesday 03/05/2023, 16:34:37] Cleaning up "tmp/" folder...
[Wednesday 03/05/2023, 16:34:37] [WinError 32] Impossibile accedere al file. Il file è utilizzato da un altro processo: 'tmp/whatsapp.tar'
[Wednesday 03/05/2023, 16:34:37] >>> I am in view_extract.kill_me(reason=)
```

My device: Honor View 10 (BKL-L09)
OS: Windows 10

**Comment by YuvrajRaghuvanshiS** [comment]
try running with `--tar-only`, and extract manually

**Comment by Frankprog03** [comment]
@aditeyabaral the problem seems to come out when extracting `msgstore.db`, causing it to be corrupted (Unfortunately this is the protagonist file here...). Also, the key doesn't exist in the archive. The extracted .ab file is approximately 5GB in my case, but the resulting tar is only 1.5GB. I'm not sure if this is normal as I have no experience with android backups. My guess is that for some reason the conversion from ab to tar is going wrong, so maybe the problem is with abe.jar... (?)

**Comment by aditeyabaral** [comment]
@Frankprog03 The `msgstore.db` file is already decrypted, so there is no need for a key actually. The issue is, as you said, the file getting corrupted while converting from `.ab` to `.tar`. We will have to wait for @YuvrajRaghuvanshiS to give us a better idea of how to debug this issue.

**Comment by Frankprog03** [comment]
@aditeyabaral yeah, I know. The key file could have been useful if it had been extracted before the EOF, because then I can easily copy and decrypt `msgstore.db.crypt14`, which can be read normally.

**Comment by aditeyabaral** [comment]
@Frankprog03 can the script be modified to copy the key file first to the system? Then we can decrypt any of the files later as well. Unfortunately I do not have much idea about backups so I am not sure how accurately this would work.

**Comment by YuvrajRaghuvanshiS** [comment]
change 
```python
def clean_tmp():
    custom_print('>>> I am in view_extract.clean_tmp()', is_print=False)
    if(os.path.isdir(tmp)):
        custom_print(f'Cleaning up \"{tmp}\" folder...', 'yellow')
        shutil.rmtree(tmp)
```

to 
```python
def clean_tmp():
    pass
```
in view_extract so that it avoids cleaning the ab file

**Comment by Frankprog03** [comment]
@YuvrajRaghuvanshiS wow! I will try it as soon as I can. Thanks.

**Comment by Frankprog03** [comment]
@YuvrajRaghuvanshiS Ok, you solved my problem but it is weirder than expected. I changed the `clean_tmp()` function to
```
def clean_tmp():
    pass
```
and I executed the script to convert the ab with the script you provided. But the script ran with no problems at all. It seems  `clean_tmp()` somehow conflicted with the conversion but I don't know how. I don't care anymore, though :)

Now I successfully got all the expected files in the extracted folder. Thanks.

**Comment by YuvrajRaghuvanshiS** [comment]
It seems it tried to clean to the tmp before it actually finished the unpacking (ab -> tar) and doing that it snatched the ab file from abe.jar, hence the size difference. It works I also don't know why. Anyways I am happy it all worked out for you.

**Comment by UsamaAshfaq** [comment]
@Frankprog03 Can you plz make a fork of this repo with modified code, so that we non-programmers can also benefit from it. 

Thankyou.

**Comment by Frankprog03** [comment]
@UsamaAshfaq there it is https://github.com/Frankprog03/WhatsApp-Key-Database-Extractor/tree/master
I think this is not and shouldn't be a permanent fix, just a "patch".
