### ISSUE TITLE
[WinError 2] The system cannot find the file specified: 'tmp/whatsapp.tar'

### ISSUE THREAD

**Issue by khairulanwarDeen** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#116]
After backup and reinstallation of original whatsapp. I was prompted to key in name for user and password keyed in device. However it cannot continue because if the error :[WinError 2] The system cannot find the file specified: 'tmp/whatsapp.tar'

**To Reproduce**
1. run wa_kdbe.py
2. run backup on handphone
3. See error

![image](https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/assets/59588004/97f76c87-e5ff-48f3-84f5-e7707751ebdc)

**Comment by YuvrajRaghuvanshiS** [comment]
wierd, it somehow got deleted during the process somehow and I am not sure why, maybe the antivirus did it, you can try `--tar-only` to stop at the tar step and go inside of that yourself.
Here are the file paths
https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/blob/18fecd8447b75d1b71bc2ea38d6b8cc611df14a3/view_extract.py#L266C9-L266C9
