### ISSUE TITLE
Ask user to copy msgstore.db to /sdcard.

### ISSUE THREAD

**Issue by roberts01** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#13]
This would be a really cool feature to work in conjunction with https://github.com/jukefoxer/Signal-Android

**Comment by rschuppan** [comment]
To clarify, I mean on the phone.

**Comment by YuvrajRaghuvanshiS** [comment]
> 
> 
> To clarify, I mean on the phone.

yes I understood that.

**Comment by YuvrajRaghuvanshiS** [comment]
TODO : What if user does not connect device during view_extract.py
