### ISSUE TITLE
Possibility to run this tool directly from the phone (really longterm feature)

### ISSUE THREAD

**Issue by roberts01** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#14]
I don't even know if that's possible, but I think a really longterm goal could be that this tool can run on the device with WhatsApp completly without a Laptop / PC necessary.

Maybe using somethin like this: https://github.com/tytydraco/ladb

**Comment by YuvrajRaghuvanshiS** [comment]
Tried that in [termux edition](https://github.com/yuvrajraghuvanshis/WhatsApp-Key-Database-Extractor/tree/termux). The way you proposed this is to work my making an android app first and then somehow running this entire python based project inside that. However no matter what I did I could not "fluff" whatsapp.ab android backup file to "whatsapp.tar" using abe.jar on android when I was working on termux edition. I could not fix this and then did not try further.

**Comment by YuvrajRaghuvanshiS** [comment]
Also as of now only latest stock android supports explicit wireless debugging via TCP, toggle on option in developer option. Other variants of android or skinned android like MIUI do not provide that option and to enable wireless debugging you first need to run `adb tcpip <port>` from computer which defeats the purpose of No Computer.

**Comment by rschuppan** [comment]
Okay I understand. 
1. If you dont mind I'd like to look a bit deeper into the fluffing topic. Can you reccomend some Google topics / terms to get started, 'cause I've never heard of fluffing before. 

Well, than this would only be relevant for Android 10(?) upwards, right? But, seeing as this would perspectively in that direction, I think it would be mwort looking into more.

**Comment by YuvrajRaghuvanshiS** [comment]
Fluffing is a made up term. 
You can start from [here](https://sourceforge.net/projects/adbextractor/)

**Comment by YuvrajRaghuvanshiS** [comment]
Also adb backup is deprecated. So I don't think this method of extracting will work in newer versions of android.

**Comment by rschuppan** [comment]
Do you know if there is a followup command planned?

**Comment by YuvrajRaghuvanshiS** [comment]
I can't say. I have set Termux Edition as No Longer Maintained. I stopped all work there a while ago and not planning to continue before getting any solid workaround. You are more than welcome to do your research on this topic and contribute.

**Comment by rschuppan** [comment]
Okay I will look into it.

**Comment by rschuppan** [comment]
https://github.com/nelenkov/android-backup-extractor the original source of the backup extractor

**Comment by rschuppan** [comment]
Okay so apperantly adb backup just calls a function called bu.
https://github.com/nelenkov/android-backup-extractor/issues/83#issuecomment-769028915 
Thats good news, right?

**Comment by YuvrajRaghuvanshiS** [comment]
https://youtu.be/qFJVUnXmVMI Requires two phones. Workable tho, requires some changes in commands, thinking of making that work in termux.

**Comment by roberts01** [comment]
Would be cool if you could get this running, but without the second phone.

**Comment by YuvrajRaghuvanshiS** [comment]
This requires compiling it into an android app.

**Comment by YuvrajRaghuvanshiS** [comment]
He was mentioning [Termux-ADB](https://github.com/MasterDevX/Termux-ADB) and that was how I initially approached this problem and named my branch based on that (Termux-Edition), however this requires you to either have wireless debugging option enabled in developer option which only AOSP has in latest versions and not modified ROMs like MIUI or Samsung's or run `adb tcpip 5555` to get wireless debugging going on your device which requires computer.

**Comment by roberts01** [comment]
So besides the "'ADB over network' only on Android 11+ via phone enableble" problem (which will solve itself over time I think), if I run the adb `adb tcpip 5555` via PC, the Termux edition should work then right?

**Comment by YuvrajRaghuvanshiS** [comment]
Yes that'd work but that breaks at converting .ab to .tar and I could not figure out why, here. #3

**Comment by roberts01** [comment]
I thought the extraction happens after the decrytion?

**Comment by YuvrajRaghuvanshiS** [comment]
yes, decryption then conversion to tar and then extraction.

**Comment by roberts01** [comment]
Might want to move away from the Haxus repo, as it is no longer maintained, and instead use the same script in an updated version from here https://github.com/MasterDevX/Termux-Java

**Comment by YuvrajRaghuvanshiS** [comment]
You're working on Termux-Edition, that's your choice. :D

**Comment by roberts01** [comment]
true, but its still your project ;-)

**Comment by roberts01** [comment]
But if we get the damn extraction done, then this should work, right?

**Comment by YuvrajRaghuvanshiS** [comment]
That's open to contribution.
And I'm working (almost finished except #24) on making this work via TCP so this script can work on any phone without USB cable.

**Comment by YuvrajRaghuvanshiS** [comment]
> But if we get the damn extraction done, then this should work, right?

Yes

**Comment by roberts01** [comment]
> That's open to contribution.
> And I'm working (almost finished except #24) on making this work via TCP so this script can work on any phone without USB cable.

Oh that sounds cool tho!
Mind just approving the pulls? :-)

**Comment by roberts01** [comment]
> Yes that'd work but that breaks at converting .ab to .tar and I could not figure out why, here. #3

Also could you point me to where in your code the decryption-conversion-extraction process happens?

**Comment by YuvrajRaghuvanshiS** [comment]
> Also could you point me to where in your code the decryption-conversion-extraction process happens?

https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/blob/40398255810530114fa2d70de81e53f4582830cd/view_extract.py#L54

**Comment by roberts01** [comment]
So, as #3 is really the only thing that is still in the way, I propose to merge the two issues (is that possible?). 
Also, I think it might be a good idea to rename the Termux version to like "Mobile" or "App" version, as I do not think a lot of people (besides the ones that work with it of course) know what Termux is.

**Comment by YuvrajRaghuvanshiS** [comment]
Issues are closed, pulls are merged.

**Comment by YuvrajRaghuvanshiS** [comment]
Only link to termux is from master prerequisites section. I think that is understandable.

**Comment by roberts01** [comment]
I understand. I think this issue can be closed then.
