### ISSUE TITLE
Ship project with APK instead of hardcoded links.

### ISSUE THREAD

**Issue by rschuppan** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#15]
Right now you have references to WhatsApps page and Whatscrypts page hardcoded in your tool.
I suggest you take those ressources (the .apk files) and store them someplace that you can control,

My point is, if WhatsApp and or whoever is behind Whatscrypt decides to moves or change their backend, the tool is broken, and noone wants that.

**Comment by rschuppan** [comment]
I suggest you either deliver the APKs as part of your tool, or you place them on a server (if you own one) and insert references to this server instead.

**Comment by YuvrajRaghuvanshiS** [comment]
APKs are closed source. I can't risk installing those on user device if I don't know what's in there. 
If for some reason any of link won't work I'll add new one.

**Comment by rschuppan** [comment]
But aren't you doing that already?

**Comment by YuvrajRaghuvanshiS** [comment]
I download legacy whatapp yes. But I'll not be held responsible if that contains malware (FYI it does not, just a metaphor). And the re-installation part, I reinstall same apk which was on user device

**Comment by rschuppan** [comment]
Okay then what are the links for?

**Comment by YuvrajRaghuvanshiS** [comment]
legacy whatsapp.

**Comment by rschuppan** [comment]
Okay but you KNOW they are clean, so you can just put them in the package as well. 
And right now the links just increase the probability of instability.

**Comment by rschuppan** [comment]
And if it contains malware, you'll be accused anyway, no matter from where you install it.
