### ISSUE TITLE
IndentationError: unexpected unindent

### ISSUE THREAD

**Issue by byRoadrunner** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#17]
**Describe the bug**
When running the script the following error appears, all dependencies are installed. I also tried it on a seperate device.

**To Reproduce**
1. run 'python wa_kdbe.py'
2. See error (i removed the full path of the script file, should not be relevant for this bug)

**Expected behavior**
Run the script to run without errors.

**Screenshots**
Not needed

**Terminal output**
`Traceback (most recent call last):
  File "wa_kdbe.py", line 10, in <module>
    from view_extract import ExtractAB
  File "view_extract.py", line 140
    if __name__ == "__main__":
    ^
IndentationError: unexpected unindent`

**Desktop:**
 - OS: Windows 10

**Smartphone:**
 - Device: OnePlus 6T
 - Android Android 10
 - Version ONEPLUS A6013_41_201116

**Comment by YuvrajRaghuvanshiS** [comment]
I added some features this morning and able to reproduce this on my machine. Fixing it now.

**Comment by YuvrajRaghuvanshiS** [comment]
Try a `git pull origin` and re-run `wa_kdbe.py`

**Comment by byRoadrunner** [comment]
Now the script executes but I only receive the following output:
`* daemon not running. starting it now on port 5037 *
* daemon started successfully *
Could not find any connected device. Is USB Debugging on?

Exiting...`

But if I check with adb devices my device shows up as attached device. And yes, I enabled USB Debugging in dev settings.

**Comment by YuvrajRaghuvanshiS** [comment]
Find and kill `adb.exe` from task manager.

**Comment by byRoadrunner** [comment]
It seems your adb binary is not working in my case. If I use adb (installed on my system) i get a correct list of my devices. But if I use your provided binary the list is empty.

**Comment by YuvrajRaghuvanshiS** [comment]
Then you may do this. Copy your adb executable to bin folder and then continue, make sure name of file is `adb.exe` after getting copied.

**Comment by YuvrajRaghuvanshiS** [comment]
try now with `git pull origin`

**Comment by byRoadrunner** [comment]
Thank you. Now it is working. What exactly should I enter if it asks me for reference name for my user?

**Comment by YuvrajRaghuvanshiS** [comment]
Your name, default is 'user' that is just to put everything inside 'extracted\user' folder.

**Comment by byRoadrunner** [comment]
Okay, because when I tried with name: Joschua I got this message:
`Successfully 'fluffed' tmp/whatsapp.ab tmp/whatsapp.tar
[WinError 3] Das System kann den angegebenen Pfad nicht finden: 'extracted/Joschua'`

**Comment by YuvrajRaghuvanshiS** [comment]
Can you re-run and send me entire console output?

**Comment by byRoadrunner** [comment]
`Found Java installed on system.

Please read above instructions carefully ↑ . Continue? (default y) :
Connected to ONEPLUS A6013
WhatsApp V2.21.1.16 installed on device
Found legacy WhatsApp V2.11.431 apk in helpers/ folder
Backing up WhatsApp 2.21.1.16 apk, the one installed on device to tmp/WhatsAppbackup.apk
Folder tmp/ already exists.
/data/app/com.whatsapp-sc4MjcOPe6wwlgcgf57CjQ==/base.apk: ...le pulled, 0 skipped. 32.8 MB/s (31604309 bytes in 0.920s)
Apk backup complete.
Uninstalling WhatsApp, skipping data.
Success
Uninstalled.
Installing legacy WhatsApp V2.11.431, hold tight now.
Performing Streamed Install
Success
Installation Complete.
Backing up WhatsApp data as tmp/whatsapp.ab. May take time, don't panic.
WARNING: adb backup is deprecated and may be removed in a future release
Now unlock your device and confirm the backup operation...
Done backing up data.
Reinstallting original WhatsApp.
Performing Streamed Install
Success

Our work with device has finished, it is safe to remove it now.

Found whatsapp.ab in tmp folder. Continuing
Enter a reference name for this user. : Joschua
Enter same password which you entered on device when prompted earlier. : _redacted_
Successfully 'fluffed' tmp/whatsapp.ab tmp/whatsapp.tar
[WinError 3] Das System kann den angegebenen Pfad nicht finden: 'extracted/Joschua'`

Also I have the problem that if I try to start WhatsApp after running the script it instantly crashes (Version 2.21.1.16) the only way working is deleting the user data of WhatsApp and then restoring the local backup.

**Comment by byRoadrunner** [comment]
Should i create the extracted folder on the repo root? Because at the moment there is no extracted folder.

**Comment by YuvrajRaghuvanshiS** [comment]
Yes folder structure should be like this 

![image](https://user-images.githubusercontent.com/52948878/106464456-b220f400-64be-11eb-94cb-f67b7035d232.png)

**Comment by byRoadrunner** [comment]
Okay, thank you. Now it works. The issue with WhatsApp crashing still persists. It took arround 30 seconds to take the backup.

**Comment by YuvrajRaghuvanshiS** [comment]
> The issue with WhatsApp crashing still persists

This happens because of some data structure differences b/w latest and old version, or something like this. That's the reason for banner warning to take backup.

> It took arround 30 seconds to take the backup

This means backup creation went just fine. On some devices it does not get created in the first place.

Can you see msgstore.db ?

**Comment by byRoadrunner** [comment]
> Can you see msgstore.db ?
Yes I can see it. The size is 250 MB.

**Comment by YuvrajRaghuvanshiS** [comment]
Glad it all worked out.
