### ISSUE TITLE
adb backup not working on TCP

### ISSUE THREAD

**Issue by YuvrajRaghuvanshiS** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#2]
it does not fetch backup. Send help...

**Comment by rschuppan** [comment]
what is / was the problem here?

**Comment by YuvrajRaghuvanshiS** [comment]
adb could not create whatsapp.ab [over tcp](https://stackoverflow.com/questions/2604727/how-can-i-connect-to-android-with-adb-over-tcp)
