### ISSUE TITLE
Invalid option error when installing dependencies | macOS

### ISSUE THREAD

**Issue by shloak17107** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#37]
**Describe the bug**
Error at line 24 in `linux_dependencies.sh`. I don't think there is any `-y` option for `brew install`.

**To Reproduce**
1. Run `./bin/linux_dependencies.sh`

**Screenshots**
<img width="559" alt="Screen Shot 2021-02-22 at 19 15 17" src="https://user-images.githubusercontent.com/31565271/108736075-4e7c6a80-7542-11eb-9dda-b01c65e142d2.png">

**Desktop:**
 - OS: macOS Big Sur

**Comment by YuvrajRaghuvanshiS** [comment]
Working on it...

**Comment by YuvrajRaghuvanshiS** [comment]
try now.

**Comment by shloak17107** [comment]
Issue solved
