### ISSUE TITLE
Problems when installing dependencies | macOS

### ISSUE THREAD

**Issue by shloak17107** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#38]
**Describe the bug**
Multiple errors when installing dependencies on macOS

**To Reproduce**
1. Run `brew cleanup` and `brew upgrade`
2. Run `chmod +x bin/linux_dependencies.sh`
3. Run `./bin/linux_dependencies.sh`
4. See errors

**Terminal output**
<img width="634" alt="Screen Shot 2021-02-22 at 22 53 38" src="https://user-images.githubusercontent.com/31565271/108762160-cf4a5f00-7560-11eb-9bc9-623e837eb1e2.png">

**Desktop:**
 - OS: macOS Big Sur

**Comment by YuvrajRaghuvanshiS** [comment]
adb curl grep tar openjdk-11-jdk p7zip-full
These are the packages supposed to be installed by running linux_dependencies.sh. You need to find their alternatives for mac and check if that works for you. If it does then please list those alternatives here so I can update this script accordingly.

**Comment by shloak17107** [comment]
`android-platform-tools` can be used in place of `adb`
https://formulae.brew.sh/cask/android-platform-tools#default

`curl` already works

`grep` already works

`gnu-tar` can be used in place of `tar`
https://formulae.brew.sh/formula/gnu-tar

`openjdk-11-jdk` is just Java right? I already have Java 12.0.1 installed on my Mac, won't that work?

`p7zip` can be used in place of `p7zip-full`
https://formulae.brew.sh/formula/p7zip#default

**Comment by YuvrajRaghuvanshiS** [comment]
> `openjdk-11-jdk` is just Java right? I already have Java 12.0.1 installed on my Mac, won't that work?

I believe they are same.

**Comment by YuvrajRaghuvanshiS** [comment]
Try this `brew install openjdk`

**Comment by shloak17107** [comment]
> Try this `brew install openjdk@11`

Yes `openjdk@11` installs successfully

Will it conflict with Java 12?
Screenshot:
<img width="716" alt="Screen Shot 2021-02-23 at 18 20 38" src="https://user-images.githubusercontent.com/31565271/108865046-d5dde280-7603-11eb-9764-629e320fa3be.png">

**Comment by YuvrajRaghuvanshiS** [comment]
> Will it conflict with Java 12? 

Can't say.

**Comment by shloak17107** [comment]
All packages install successfully
