### ISSUE TITLE
com.whatsapp does not exist, fails to install legacy WhatsApp | macOS

### ISSUE THREAD

**Issue by shloak17107** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#39]
**Describe the bug**
Upon running `python3 wa_kdbe.py`, `adb` does not find `/data/app/com.whatsapp-1/base.apk`. Then, it fails to install `helpers/LegacyWhatsApp.apk`.

**To Reproduce**
1. Device connected via cable and USB debugging enabled
2. Python requirements installed and dependencies installed
3. Run `python3 wa_kdbe.py`

**Screenshots**
<img width="716" alt="Screen Shot 2021-02-23 at 19 47 03" src="https://user-images.githubusercontent.com/31565271/108877056-e85e1900-760f-11eb-8ef0-34e9faa118ff.png">

**Desktop:**
 - OS: macOS Big Sur

**Smartphone:**
 - Device: Motorola G4 Plus
 - Android Nougat
 - Version 7.0

**Comment by YuvrajRaghuvanshiS** [comment]
If terminal is outputting `/data/app/com.whatsapp-1/base.apk` it this meaning it sure exists, now why isn't this pulling it to laptop is concering. 
Run this : 
```
adb shell pm path com.whatsapp
adb pull <path> ./test.apk
```
where <path> is the output of first command. Like `/data/app/com.whatsapp-1/base.apk` in your case.

**Comment by shloak17107** [comment]
```
➜  WhatsApp-Key-Database-Extractor git:(master) ✗ adb shell pm path com.whatsapp
package:/data/app/com.whatsapp-1/base.apk
➜  WhatsApp-Key-Database-Extractor git:(master) ✗ adb pull /data/app/com.whatsapp-1/base.apk ./test.apk
adb: error: remote object '/data/app/com.whatsapp-1/base.apk' does not exist
```

**Comment by YuvrajRaghuvanshiS** [comment]
That is definitely a bug but not on my side. 
Try this.
```
adb shell pm path com.whatsapp
adb shell cp <path> /sdcard/temp.apk
adb pull /sdcard/temp.apk ./whatsapp.apk
```

**Comment by shloak17107** [comment]
Successfully pulled
```
➜  WhatsApp-Key-Database-Extractor git:(master) ✗ adb shell pm path com.whatsapp
package:/data/app/com.whatsapp-1/base.apk
➜  WhatsApp-Key-Database-Extractor git:(master) ✗ adb shell cp /data/app/com.whatsapp-1/base.apk /sdcard/temp.apk
➜  WhatsApp-Key-Database-Extractor git:(master) ✗ adb pull /sdcard/temp.apk ./whatsapp.apk
/sdcard/temp.apk: 1 file pulled, 0 skipped. 12.9 MB/s (32340776 bytes in 2.385s)
```

**Comment by YuvrajRaghuvanshiS** [comment]
Find me that man who said do Computer Science LoL, committing this change.
