### ISSUE TITLE
adb fails to install legacy WhatsApp | macOS [INSTALL_FAILED_VERSION_DOWNGRADE]

### ISSUE THREAD

**Issue by shloak17107** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#40]
**Describe the bug**
After backing up and uninstalling the existing Whatsapp on the device, the script proceeds to install the legacy WhatsApp. However, it runs into the following error: `adb: failed to install helpers/LegacyWhatsApp.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]`.

**To Reproduce**
1. Device connected via cable to Mac and USB debugging enabled
2. Python requirements installed and dependencies installed
3. Run `python3 wa_kdbe.py`

**Screenshots**
<img width="716" alt="Screen Shot 2021-02-23 at 21 05 42" src="https://user-images.githubusercontent.com/31565271/108887141-e64d8780-761a-11eb-9998-7ce989bb7eea.png">

**Desktop:**
 - OS: macOS Big Sur
 
**Smartphone:**
 - Device: Motorola G4 Plus
 - Android Nougat
 - Version 7.0

**Comment by YuvrajRaghuvanshiS** [comment]
`[INSTALL_FAILED_VERSION_DOWNGRADE].` is a known bug. Fix it by running with `python wa_kdbe.py --allow-reboot`

**Comment by Pandoraluke** [comment]
Today it does not work anymore, it gives: 

<img width="1092" height="822" alt="Image" src="https://github.com/user-attachments/assets/677e4b19-90df-4e1f-8973-d3ee5d8bd037" />
