### ISSUE TITLE
ScrCpy tests.

### ISSUE THREAD

**Issue by YuvrajRaghuvanshiS** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#41]
**Is your feature request related to a problem? Please describe.**
ScrCpy tests on all OSs

Hey @shloak17107 I have recently added [scrcpy](https://github.com/Genymobile/scrcpy) for non windows devices. It is a tool to mirror screen as well as control it (input keys, simulate touches etc.) Would you like to test those?

Get scrcpy 

```
chmod +x bin/linux_dependencies.sh
sudo ./bin/linux_dependencies.sh
```

Run with --scrcpy flag

```
python wa_kdbe.py --scrcpy
```

**Comment by shloak17107** [comment]
What should I be able to see with `scrcpy`?

**Comment by YuvrajRaghuvanshiS** [comment]
Your android screen in real time.

**Comment by shloak17107** [comment]
Nothing opens for me on my Mac.

**Comment by YuvrajRaghuvanshiS** [comment]
Did you re install dependencies? 
Try running scrcpy by typing in terminal `scrcpy` if that works.

**Comment by shloak17107** [comment]
My bad, forgot to run with `--scrcpy` flag.
It mirrors my screen just before reboot but doesn't after reboot.

**Comment by YuvrajRaghuvanshiS** [comment]
Yeah that's the issue. But again entire point of using scrcpy was to control device when (it is running on tcp and) you don't have physical access of device. So you can enter password, unlock device etc. and on tcp it does not reboot.
