### ISSUE TITLE
sh: xdg-open: command not found | macOS

### ISSUE THREAD

**Issue by shloak17107** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#42]
**Describe the bug**
At the end of the script, the user folder is deleted and the script proceeds to exit. Just after the exiting message, I get the error `sh: xdg-open: command not found`.

**To Reproduce**
1. Device connected via cable to Mac and USB debugging enabled
2. Python requirements installed and dependencies installed
3. Run python3 wa_kdbe.py
4. Successfully uninstall WhatsApp, install legacy, and reinstall original WhatsApp.
5. See error when exiting

**Screenshots**
<img width="716" alt="Screen Shot 2021-02-24 at 10 40 28" src="https://user-images.githubusercontent.com/31565271/108964600-b76ff980-768c-11eb-8096-ce8d8b7076c7.png">

**Desktop:**
 - OS: macOS Big Sur

**Smartphone:**
 - Device: Motorola G4 Plus
 - Android Nougat
 - Version 7.0

**Comment by YuvrajRaghuvanshiS** [comment]
I made it to automatically open that folder so you don't have to go through file system. That works with all linux system. How can you open a folder in file explorer using terminal on mac?

**Comment by YuvrajRaghuvanshiS** [comment]
The `open` command opens a file (or a directory or URL), just as if you had double-clicked the file's icon. If no application name is specified, the default application as determined via LaunchServices is used to open the specified files.
I'll modify script accordingly.
