### ISSUE TITLE
Fork MasterDevX Termux-Java to include policy

### ISSUE THREAD

**Issue by roberts01** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#43]
Have to fork the mentioned project:
https://github.com/MasterDevX/Termux-Java
to include the policy below:
https://www.oracle.com/java/technologies/javase-jce8-downloads.html
Also reduces dependencies, as this is a working java-termux version.

**Comment by YuvrajRaghuvanshiS** [comment]
You really created an issue for this.

**Comment by roberts01** [comment]
Of couse I did😉

**Comment by YuvrajRaghuvanshiS** [comment]
This is not worth investing time and efforts into. Creating whatsapp.ab file on termux without password and later creating a entrypted 7z file (already implemented) for safekeeping of database and key file is enough since whatsapp.ab is temporary and gets deleted eventually and there is no reason for anyone to keep whatsapp.ab with them and even if there is they can keep it safe on their own.

If in future if there is a corner case where nopass.ab is not getting unpacked into nopass.tar they can simply download those files from URl and get it working.

**Comment by roberts01** [comment]
I don't follow...

**Comment by roberts01** [comment]
What do you mean, can you explain please?

**Comment by YuvrajRaghuvanshiS** [comment]
Yes I was out for the day so couldn't  reply. Which part are you not gettign?

**Comment by roberts01** [comment]
How will we get the msgstore.db if we don't decompress the .ab file with the java tool?

**Comment by YuvrajRaghuvanshiS** [comment]
> How will we get the msgstore.db if we don't decompress the .ab file with the java tool?

We can unpack .ab file to .tar but currently can't unpack those ab file which are encrypted (user entered some password on backup screen)

**Comment by YuvrajRaghuvanshiS** [comment]
We can simply ask user to leave that empty or I can make this script in such a way that user does not have to even click his phone. I can send touch input.

**Comment by roberts01** [comment]
Oh thats great!

**Comment by roberts01** [comment]
https://forum.xda-developers.com/t/guide-how-to-extract-create-or-edit-android-adb-backups.2011811/ here is written where the policy has to be put

**Comment by roberts01** [comment]
Well I think backups are encrypted by default, but no idea...

**Comment by roberts01** [comment]
> > How will we get the msgstore.db if we don't decompress the .ab file with the java tool?
> 
> We can unpack .ab file to .tar but currently can't unpack those ab file which are encrypted (user entered some password on backup screen)

How do you plan to do that?

**Comment by YuvrajRaghuvanshiS** [comment]
> Well I think backups are encrypted by default, but no idea...

Yes sometimes, if desktop backup is already set.

**Comment by YuvrajRaghuvanshiS** [comment]
> How do you plan to do that?

Telling user not to enter password.

**Comment by roberts01** [comment]
I mean the decompression part XD

**Comment by YuvrajRaghuvanshiS** [comment]
With recent abe.jar release which Nelekov released. That is working with termux

**Comment by roberts01** [comment]
I thought you wanted to scrap the whole JAVA part. Okay so we only need the policy if the backup's encrypted right?

**Comment by YuvrajRaghuvanshiS** [comment]
> Okay so we only need the policy if the backup's encrypted right?

Exactly

**Comment by roberts01** [comment]
Cool, so no passwords

**Comment by YuvrajRaghuvanshiS** [comment]
No passwords.

**Comment by YuvrajRaghuvanshiS** [comment]
I will work on it after 10 days, I'm busy with exams.

**Comment by roberts01** [comment]
ok

**Comment by roberts01** [comment]
okay, downloaded the unlimited policy

**Comment by roberts01** [comment]
okay forked and installed, try it

**Comment by roberts01** [comment]
wget https://raw.githubusercontent.com/roberts01/java/master/installjava && bash installjava 

https://github.com/roberts01/Termux-Java
