### ISSUE TITLE
Install of Legacy Whatsapp version fails.

### ISSUE THREAD

**Issue by jinucompute** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#44]
**Describe the bug**
When it tries to install the Legacy Whatsapp version. It does not install. It fails. The python script does not give an error but when you check the device there is no whatapp installed. Then I tried to execute the command manually and it fails giving the error
Failure [-26: Package com.whatsapp new target SDK 19 doesn't support runtime permissions but the old target SDK 23 does.]

**To Reproduce**
1. adb install -r -d  helpers/LegacyWhatsApp.apk

**Expected behavior**
The old version whatsapp should be installed

**Screenshots**

**Terminal output**

```
Performing Streamed Install
adb: failed to install helpers/LegacyWhatsApp1.apk: Failure [-26: Package com.whatsapp new target SDK 19 doesn't support runtime permissions but the old target SDK 23 does.]
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device: Samsung S7 Edge
 - Android: Oreo
 - Version: R16NW.G935FXXU8ETI2 

**Additional context**

**Comment by YuvrajRaghuvanshiS** [comment]
```
> https://www.b4x.com/android/forum/threads/failed-to-install-app-apk-failure-26.80288/
Uninstall the previously installed app and it will work.

This error happens when you install an app with targetSdkVersion >= 23 and then try to reinstall it with targetSdkVersion < 23.
```

Try with `python wa_kdbe.py --allow-reboot`

**Comment by YuvrajRaghuvanshiS** [comment]
It is most likely happening because of the way original whatsapp is being uninstalled `adb uninstall -k com.whatsapp` which keeps all the data inside it's dedicated directory. And legacy whatsapp can not be installed over that data.

**Comment by jinucompute** [comment]
> --allow-reboot

I tried with allow-reboot. It reboots the device after uninstall but then again same issue

**Comment by YuvrajRaghuvanshiS** [comment]
I need some time to look into that.

**Comment by jinucompute** [comment]
I think i figured out why this error is coming. This is because Samsung S7 Edge (the version i have) came with Whatsapp as part of the System apps. So there is no way to uninstall it. I can only disable it .

**Comment by YuvrajRaghuvanshiS** [comment]
This could be it. I never tested this tool that way.

**Comment by jinucompute** [comment]
I tried on another device. Here it installs the legacy Whatsapp but when i start the legacy version it just gives error "Your phone Date is inaccurate". There is no option to move forward. What do i do next ?

**Comment by YuvrajRaghuvanshiS** [comment]
Ignore this warning. There should be a yellow text saying that..

**Comment by jinucompute** [comment]
I get a full screen with this error and a button to Adjust time. How do i proceed beyond this screen ? If i click on the button to Adjust Time, it takes me to the device clock settings.

**Comment by YuvrajRaghuvanshiS** [comment]
You don't need to do anything with whatsapp at this point in time. Press enter key on terminal where it says "press any key after running whatsapp for a while. Ignore incorrect time warning." and it will automatically open a backup activity on your android.

**Comment by YuvrajRaghuvanshiS** [comment]
You should run whatsapp for a second or two before pressing enter tho. Just do random swipes or something.

**Comment by jinucompute** [comment]
Thanks this worked.
