### ISSUE TITLE
It says SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by polmillang** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#49]
**Describe the bug**
When I copy the first line of code into Python: 
git clone https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor.git && cd WhatsApp-Key-Database-Extractor

it says that there is a SyntaxError: invalid syntax

I cannot get past this.

Sorry for my low level.

**Comment by ForceGT** [comment]
![image](https://user-images.githubusercontent.com/31688051/113680939-09219000-96df-11eb-93ed-d5070edb12b4.png)
Seems to work for me 
Can you give more info like which python version , which OS are you using?

**Comment by ForceGT** [comment]
Also check if you have ```git``` installed on your system 
If not then [Go Here](https://github.com/git-guides/install-git)

**Comment by YuvrajRaghuvanshiS** [comment]
Or you can continue without git by [downloading zip from here](https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/archive/refs/heads/master.zip).
1. Download it. 
2. Extract it.
3. Go inside folder.
4. Open terminal/cmd/powershell there and continue from second command.

Feel free to re-open the issue if problem persists.
