### ISSUE TITLE
Running "python wa_kdbe.py" isn't leaving First run loop

### ISSUE THREAD

**Issue by roberts01** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#56]
**Describe the bug**
when I run this, there is only "Running for first time" a bunch of checks on packages and pre reqs and thrn the console gets cleared, without actually running the main part. 

Weirdly enough, if i just double click the file, it works fine. 

 - OS: [e.g. Windows 10]
- Python 3.9

**Comment by YuvrajRaghuvanshiS** [comment]
Paste the terminal output here.
Also is this happening while running for first time or every time?

**Comment by roberts01** [comment]
I would, but the output disappears before I can copy anything😞.

Also it happens every time, that's why I considered it a bug.

**Comment by YuvrajRaghuvanshiS** [comment]
Try to a screen recording or video.

**Comment by YuvrajRaghuvanshiS** [comment]
> I would, but the output disappears before I can copy anything😞.

fixed in #57

**Comment by roberts01** [comment]
ah perfect, closing this one
