### ISSUE TITLE
Urgent - Need genuine link of WhatsApp V2.11.431

### ISSUE THREAD

**Issue by Ealdwritere** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#58]
It appears that the official Whatsapp page has removed v.2.11.431 and this legacy version it is not available for download. www.whatcrypt.com is down, and this download link for legacy whatsapp is also not available. 

This is causing the program to crash when it attempts to download legacy Whatsapp from those links.

Is it possible to provide another download link in the source code?

[18:05:23.616444] If you haven't already, it is adviced to take a WhatsApp chat backup by going to WhatsApp settings → Chat Settings → Chat Backup. Hit Enter key to continue.
[18:05:25.056248] Connected to ANE-LX2J
[18:05:26.168361] WhatsApp V2.21.7.14 installed on device
[18:05:26.175997] Downloading legacy WhatsApp V2.11.431 to helpers folder
PS C:\Users\masar\Downloads\WhatsApp-Key-Database-Extractor-master(1)\WhatsApp-Key-Database-Extractor-master>

**Comment by YuvrajRaghuvanshiS** [comment]
I'm working on it.

**Comment by YuvrajRaghuvanshiS** [comment]
testing with https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=1296

**Comment by NioBee** [comment]
Here is another site with old APK versions.. but I don't know if it is a trusted one..
https://androidapksfree.com/whatsapp-messenger/com-whatsapp/old/page/24/

[https://androidapksfree.com/whatsapp-messenger/com-whatsapp/download-old/whatsapp-messenger-apk-v2-11-431-download/](url)

**Comment by YuvrajRaghuvanshiS** [comment]
Thank you Patrizia for these links but I am very sensitive about what this repo is gonna install on user's device. I can't risk infecting anyone's device. I was looking around on WayBack machine and found old snapshot of whatsapp official download page : https://web.archive.org/web/20141111005331/http://www.whatsapp.com/android/ Implementing this now.

**Comment by YuvrajRaghuvanshiS** [comment]
![Uploading image.png…]()

**Comment by NioBee** [comment]
> Thank you Patrizia for these links but I am very sensitive about what this repo is gonna install on user's device. 

I absolutely agree with you!

**Comment by YuvrajRaghuvanshiS** [comment]
@Ealdwritere  check now after pulling recent changes.

**Comment by Ealdwritere** [comment]
> 
> 
> @Ealdwritere check now after pulling recent changes.

That's fixed it :-). Excellent job!

**Comment by YuvrajRaghuvanshiS** [comment]
Cool. Closing it. Thanks everyone
