### ISSUE TITLE
`pause` unknown and unnecessary before `quit()` on Linux

### ISSUE THREAD

**Issue by nathanael-naeri** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#59]
I noticed that the source code contains several instances of `os.system('pause')` before `quit()`. `pause` is a DOS command that is unknown on Linux. I ran into it after creating an encrypted archive of the extracted files.

Bash has a `read` builtin that can be used for that (`read [-t <seconds>] [-p <message>]`), GNU coreutils provides the `sleep` command (`sleep <seconds>`), and Python has [`time.sleep()`](https://docs.python.org/3/library/time.html#time.sleep). But it may not even be necessary to pause before quitting, as the terminal doesn't close.

**Comment by YuvrajRaghuvanshiS** [comment]
The reason to put those was to stop cmd/powershell form closing on exiting when this is run by double clicking on windows (#57 I believe ) I did not pay attention if that only DOS specific but now as you have mentioned it I realized it. 
Even python can use 
```python
input('Press \'Enter\' to continue.')
```
I will make those changes now. Thank you for bringing it to my notice
