### ISSUE TITLE
wa_contacts in wa.db empty 

### ISSUE THREAD

**Issue by biejay** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#67]
I **got the wa.db** but from there, the **wa_contacts table in** **wa.db is empty**, so I can't match the contact Names. 
To be more precise: It only has the header but no entries.

Is this an known issue?

Desktop:
Windows 10 using Anaconda -> python3

Phone:
Galaxy S10+ with Android 11

**Comment by YuvrajRaghuvanshiS** [comment]
Hey. No that is not a known issue also I am very sure this is not related to this repo. May be your WhatsApp has stored it that way only however the case is I will see it tomorrow. It's pas 2:30 in the night here.😴

**Comment by biejay** [comment]
No Problem, have a rest 👍 
I already checked all tables in wa.db and msgstore.db but couldn't find the contact names, only the jid. Its strange, as the correct wa_table is exported with correct headers, but its empty.

**Comment by YuvrajRaghuvanshiS** [comment]
Try revoking and allowing contact permission to whatsapp, reboot and then extract again. Also this time try it with `--tar-only` flag this way you can check each file of extract yourself.

**Comment by biejay** [comment]
This worked, thank you very much! 
Don't know if `--tar-only` or `--allow-reboot` did the trick, as i used both this time.

**Comment by YuvrajRaghuvanshiS** [comment]
Hah, that's the thing about programming and all this nerdy stuff, sometimes it just works God knows how😂
Closing this, be well.
