### ISSUE TITLE
Script exits after " daemon started successfully"

### ISSUE THREAD

**Issue by jaf91** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#70]
**Describe the bug**
The script ends just after getting the message " daemon  started successfully "

**To Reproduce**
1. run 'py wa_kdbe.py'
2. See error

**Screenshots**
![IMG_20210719_233217](https://user-images.githubusercontent.com/87679563/126262356-48129e6e-5a6c-4385-8c8f-0860e5e2236d.jpg)

**Terminal output**
```
Copy paste terminal output
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device: Samsung J7 
 - Android v7

**Comment by YuvrajRaghuvanshiS** [comment]
If you have even a little experience with python you can go bug hunting, I can guide you and you'll love it.
Because unfortunately I am dealing with so much that I can not work on it actively.

**Comment by jaf91** [comment]
Hi! Sorry I didn't answer before. I would be very grateful if you could guide me through the process. My knowledge about python is very basic.

**Comment by YuvrajRaghuvanshiS** [comment]
In USB mode this is the line that starts ADB server and hence puts pipelined output as "Daemon started successfully", it's the part of `init()` method, at the start of this method you can put `pdbr.set_trace()` to try to find what is causing error. It's from [pdbr](https://github.com/cansarigol/pdbr/)
https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/blob/ade4489a0b924c594388bd68e266b14ec041ef36/helpers/ADBDeviceSerialId.py#L28

**Comment by jaf91** [comment]
Hi! I reinstalled python on my computers and then updated pip. The problem is solved. Now, I have another issue but I will open other thread for it. Thanks for your time!
