### ISSUE TITLE
Source of Whatsapp .ab file

### ISSUE THREAD

**Issue by rschuppan** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#8]
How is one supposed to get the .ab file?
It is not possible to create one via "adb backup".

**Comment by YuvrajRaghuvanshiS** [comment]
It is not possible in latest version of android. But as far as my knowledge on this subject goes it is a two party approved process. Either Android OS approves it or application does (like backup in MIUI, some apps still allow data backup).
Current whatsapp version obviously does not allow that but earlier version used to do so. This tool installs that legacy version on device (after uninstalling currently installed version and "keeping" data intact) and backs up that then reinstall previously installed version.

[Here's code](https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/blob/fb74b4958477deb323fa130f036dfa7e61f1d015/wa_kdbe.py#L86) for better understanding.

**Comment by rschuppan** [comment]
Misunderstanding on my side.
