### ISSUE TITLE
Whatsapp key extractor error error during decryption please help me

### ISSUE THREAD

**Issue by BrunoHenrique229** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#86]
![erro](https://user-images.githubusercontent.com/44625772/156648225-00c32f57-27aa-4daa-9932-f048aa4242fc.PNG)

**Comment by YuvrajRaghuvanshiS** [comment]
Password must have been wrong, try again but this time just back data up don't provide any password on phone. Similarly when asked during execution just hit enter without typing in any password.

**Comment by BrunoHenrique229** [comment]
the process was completed, but when trying to read the messages decrypted by the software that is msgstore.db it appears these errors there saying that it was not possible to read the messages and says to try in older versions of whatsapp veiwer and I have already tried in several

![error 5](https://user-images.githubusercontent.com/44625772/156680766-629a2213-bac1-4e9e-8d75-f256f9f48aaf.PNG)
![erro 3](https://user-images.githubusercontent.com/44625772/156680773-cdc61606-2b14-4e34-8fec-473603ced3b3.PNG)

![error whats](https://user-images.githubusercontent.com/44625772/156680979-86a2e85b-2a0d-425b-8e46-b84d5b755663.PNG)

**Comment by YuvrajRaghuvanshiS** [comment]
https://github.com/andreas-mausch/whatsapp-viewer use it to view chats.
