### ISSUE TITLE
Error decrypting key with database in whatsapp viewer

### ISSUE THREAD

**Issue by BrunoHenrique229** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#87]
hello good I went to decrypt the database with a key extracted from the device with the program but at the time of decryption it returns this error talking about an invalid key and it was the only one I extracted from my android without root
![ola](https://user-images.githubusercontent.com/44625772/156779761-4663b544-9dbd-4f5b-90fe-89dc93cc69a7.PNG)

**Comment by YuvrajRaghuvanshiS** [comment]
This issue is not regarding my work. Please go to Andreas's repo for that.
