### ISSUE TITLE
is there any way to extract encrypted database if yes tell me a way

### ISSUE THREAD

**Issue by BrunoHenrique229** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#89]
is there any way to extract the encrypted database, if yes, tell me a way with some program option

**Comment by YuvrajRaghuvanshiS** [comment]
I don't understand, if you're asking about getting you un-encrypted database then yes, that is the sole purpose of this tool.

**Comment by BrunoHenrique229** [comment]
I'm asking which option to use to return me the encrypted database for me to decrypt it

**Comment by YuvrajRaghuvanshiS** [comment]
Encrypted database is in phone storage, you can simply copy that from phone "WhatsApp/Databases" folder. You don't require any tool for that.

**Comment by BrunoHenrique229** [comment]
The problem is when I get the key extracted by this program, I get the encrypted database trying to decrypt and it returns error in whats app viewer

**Comment by YuvrajRaghuvanshiS** [comment]
Share screenshot showing the contents this tool pulled.

**Comment by BrunoHenrique229** [comment]
![base de dados](https://user-images.githubusercontent.com/44625772/157892168-842c9365-bb1f-4b5b-8fca-4b7eecb134ab.PNG)

here are the files

**Comment by YuvrajRaghuvanshiS** [comment]
This db is not encrypted.

**Comment by YuvrajRaghuvanshiS** [comment]
Don't use decrypt function in viewer, simply open this file

**Comment by YuvrajRaghuvanshiS** [comment]
Please avoid open unnecessary issues.

**Comment by BrunoHenrique229** [comment]
![problema](https://user-images.githubusercontent.com/44625772/157892450-117ffdd0-0860-42a9-8ada-11f2159e0220.PNG)

when i try to read the conversations decrypted by the program i get this error

**Comment by YuvrajRaghuvanshiS** [comment]
Use sqlite-browser or any other db reader.

**Comment by YuvrajRaghuvanshiS** [comment]
This is not an issue of this repo.
