### ISSUE TITLE
Add support for crypt15

### ISSUE THREAD

**Issue by ElDavoo** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#94]
Hi,
Should be a pretty easy job
With crypt15 two new files have appeared, they are called encrypted_backup.key and password_data.key 
"key" will continue to exist, but only encrypted_backup.key will be used

**Comment by YuvrajRaghuvanshiS** [comment]
Can you elaborate this point?
>  "key" will continue to exist, but only encrypted_backup.key will be used

**Comment by ElDavoo** [comment]
> Can you elaborate this point?
> 
> > "key" will continue to exist, but only encrypted_backup.key will be used

If end-to-end encrypted backups are enabled, the "key" file will still continue to exist in the file system and it will not be deleted. However, it will not be used anymore: whatsapp will encrypt the backups using the file "encrypted_backup.key" and will not use "key" anymore.  
I guess that if you then disable E2E backups whatsapp starts to use "key" again



> Also can you provide the path of these files like this?
> 

Hmmm I don't know which format are you talking about, but they should be of the same type of the "key" file so if I were to take a guess:
 ```python
 {
     'encrypted_backup.key': 'apps/com.whatsapp/f/encrypted_backup.key',
     'password_data.key': 'apps/com.whatsapp/f/password_data.key',
 }
 ```

**Comment by YuvrajRaghuvanshiS** [comment]
Ah okay, I have seen some use of encrypted_backup.key on a repo but couldn't understand (I still have crypt14). 

Actually the android backup (.ab) file has a particular directory layout, similar to app's private data directory (inside /data/data/<package> folder) and unless I have the path to these files I can not implement this. Let's see if someone comments the path or I get the crypt15 first.

**Comment by ElDavoo** [comment]
to "get the crypt15" you have to manually enable end-to-end encrypted backups in whatsapp settings.

**Comment by YuvrajRaghuvanshiS** [comment]
I managed to find 'encrypted_backup.key' beside 'key' but not 'password_data.key'. For now I'm assuming that is also beside key and updating the code.

**Comment by ElDavoo** [comment]
Hi, I forgot to tell you, password_data.key will only be there if the user enters a password for encryption, not if you use the 64 character key. So it might or might not be there

**Comment by YuvrajRaghuvanshiS** [comment]
Oh, that makes sense actually. Anyways it looks for both of these and in 404 case it prints to console the link for this issue. I might add a mutual exclusiveness check for these later on.

-------- Original Message --------

**Comment by ElDavoo** [comment]
> mutual exclusiveness 

Imo the program should dump whatever it finds, the user will then have to understand what they need

**Comment by YuvrajRaghuvanshiS** [comment]
It already does that with argument '--tar-only'. It dumps the tar file, but not everyone likes to be overwhelmed so I cherrypicked a few important files.
-------- Original Message --------

**Comment by ElDavoo** [comment]
Note that password_data.key is not needed to decrypt the backup. encrypted_backup.key will always be used. However, the user might want to offline bruteforce the password, this is why it should be saved if there, but its absence does not mean anything

**Comment by YuvrajRaghuvanshiS** [comment]
Thanks for the info, I'll make a note of it in further updates.
