### ISSUE TITLE
File <fstring>, sdk_version error when running wa_kdbe.py

### ISSUE THREAD

**Issue by nkovacne** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#99]
Currently running:

  commit ab3d123249b88ed32ac50adbc84ebbda433da088 (HEAD -> master, origin/master, origin/HEAD)
  Author: David Eleazar <smartways897@gmail.com>

Dependencies are satisfied, but when running:

```
$ python3 wa_kdbe.py 
  File "<fstring>", line 1
    (sdk_version=)
                ^
SyntaxError: invalid syntax
```

Not sure why am I getting this error. However, running following commit, which I had from a time ago, it works well:

  commit 3161a19c64a13f038119ff20db13f42a701d2569 (HEAD -> master, origin/master, origin/HEAD)
  Author: Yuvraj Raghuvanshi <YuvrajRaghuvanshi.S@protonmail.com>

**Comment by YuvrajRaghuvanshiS** [comment]
I made this project when I had little knowledge of fstrings, I did not use it correctly. I had plans of rewriting this project but gave up because of my schedule. Thanks for reporting there was one more issue with fstring someone reported earlier.
